#!/bin/bash

LAUNCHER='dmenu -p "power : "'
DM=lxdm-plymouth
option=`echo -e "Riavvia\nSpegni\nLogout" | dmenu -i -p "Power : " `
if [ ${#option} -gt 0 ]
then
    case $option in
      Esci)
	      loginctl terminate-session $XDG_SESSION_ID
        ;;
      Riavvia)
        systemctl reboot
        ;;
      Spegni)
        systemctl poweroff
        ;;
      *)
        ;;
    esac
fi
